name: dop_logger
description: Log all Http request and Navigation.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.1 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  background_json_parser: any
  dio: ^4.0.6
  device_info_plus: ^8.0.0
  package_info_plus: ^3.0.2
  battery_plus: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter: